***Future skills***
1. Data
2. Software
3. Design
***Content***
- Review class OOP
- Review loop + dictionary
- Try except
- assert
- csv, json, context manager
- web scraping
- numpy pandas sqlite sklearn

In [ ]:
#Super class
class Person :
    def __init__(self, name):
        self.name = name
    def sayhi(self):
        print(f"Hi my name is {self.name}!")

class Employee(Person):
    def __init__(self, name, company):
        super().__init__(name)
        self.company = company
    def potato(self):
        print("Potato is very good")
    def sayhi(self):
        print(f"Hi my name is {self.name} and I work at {self.company}.")


In [ ]:
Bright = Person("Bright")
Toy = Employee("Toy","dTAC")
Bright.sayhi()
Toy.sayhi()

Hi my name is Bright!
Hi my name is Toy and I work at dTAC.


In [ ]:
Toy.sayhi()
Toy.potato()

Hi my name is Toy and I work at dTAC.
Potato is very good


In [ ]:
Bright.potato()

AttributeError: ignored

In [ ]:
#try-except block
try:
    print("Hello")
except ZeroDivisionError:
    print("This is error")
except NameError:
    print("Variable is not found.")
except ValueError:
    print("Please check your data type again.")
else:
    print("Done!")
finally:
     print("This is the last line.")


Hello
Done!
This is the last line.


In [ ]:
assert 1+1 == 5, "1+1 must be equal 2"

AssertionError: ignored

In [ ]:
def check_this (a,b):
    assert a+b >10, "a+b should be more than 10"
    return a+b

In [ ]:
check_this(1,3)

AssertionError: ignored

In [ ]:
#lambda function
greeting = lambda name: print("hello! "+ name)

In [ ]:
greeting("Bright")

hello! Bright


In [ ]:
odd_or_even = lambda num: "even" if num%2 == 0 else "odd"

In [ ]:
odd_or_even(5)

'odd'

In [ ]:
#list of coloured balls
balls = ['red','red','green','green','blue','blue']

In [ ]:
def summary(list_items):
    result = {}
    for item in list_items:
        if item in result:
            result[item] += 1
        else:
            result[item] = 1
    return (result)

summary(balls)

{'red': 2, 'green': 2, 'blue': 2}

In [ ]:
#comma seperated values (CSV file)


In [ ]:
!pwd

/content


In [ ]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
!mkdir newFolder

In [ ]:
!rmdir newFolder

In [ ]:
!echo hello

hello


In [44]:
!cat hotel.csv

cat: hotel.csv: No such file or directory


In [45]:
!cat Python_project.csv

cat: Python_project.csv: No such file or directory


In [ ]:
import csv #csv = module

try:
    file = open("Python_project.csv")
    data = csv.reader(file)
    file.close()
except FileNotFoundError :
    print("File not found")
else:
    print("Load data successfully.")


Load data successfully.


In [ ]:
#context manager จะเปิดแล้วปิดไฟล์แบบ Auto ต้องให้ for มันอยู่ติดกับ with clause
import csv

try:
    with open("Python_project.csv") as file:
        data = csv.reader(file)
        for row in data:
            print(row)
except:
    print("Found some errors please chack again.")

['\ufeffid', 'hotel', 'location', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Korea', '30']
['5', 'le concord', 'USA', '25']


In [ ]:
import pandas as pd

df = pd.read_csv("Python_project.csv")

df["price_double"] = df["price"]*2

df.to_csv("Python_project_modified.csv") #write file

In [ ]:
!cat Python_project_modified.csv

,id,hotel,location,price,price_double
0,1,Accor,Thailand,50,100
1,2,Ibis,Italy,60,120
2,3,London,UK,35,70
3,4,Seoul,Korea,30,60
4,5,le concord,USA,25,50


In [ ]:
#write csv file ใช้เวลาที่ไม่ได้ติดตั้ง pandas = no internet
#"w" = write mode
import csv

headers = ["id", "name", "age"]
data = [
    [1, "toy", 25],
    [2, "Bright", 23],
    [3, "jay", 44]
]
with open("newfile.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(data)

In [ ]:
cat! newfile.csv

cat: '!': No such file or directory
id,name,age
1,toy,25
2,Bright,23
3,jay,44


In [ ]:
result=[]
with open("newfile.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        result.append(row)
print(result)


[['id', 'name', 'age'], ['1', 'toy', '25'], ['2', 'Bright', '23'], ['3', 'jay', '44']]


In [ ]:
# regular expression

import re

text = "a duck walks into a bar"

result = re.search("duck", text)

if result:
    print("duck found")
else:
    print("Duck not found")

duck found


In [ ]:
# list comprehension ช่วยให้เขียนสั้นลง
numbers = [1,2,3,4,5]

In [ ]:
result = [num*2 for num in numbers]
print(result)

[2, 4, 6, 8, 10]


In [ ]:
oddNums = [num for num in numbers if num % 2 ==1]
evenNums = [num for num in numbers if num%2==0]
print(oddNums, evenNums)

[1, 3, 5] [2, 4]


In [ ]:
#json JavaScript Object Notation

In [ ]:
!ls *.txt

'Text file for Python.txt'


In [ ]:
# create new .json file
school ={
    "name" : "bootcamp",
    "batch" : 7,
    "duration" : "4 months"
}

with open("newjsonfile.json", "w") as file:
    json.dump(school, file)

NameError: ignored

In [48]:
#API
from requests import get
from time import sleep #ใช้เวลานานขึ้นในการรัน เพราะเรากำหนดไว้ ว่าเป็น 1 วิข้างล่าง
nums =list(range(1,6))

result = []
for i in nums:
    url = f"https://swapi.dev/api/people/{i}"
    response = get(url)
    data = response.json()
    row = [
        data["name"],
        data["height"],
        data["mass"],
        data["gender"]
    ]
    result.append(row)
    sleep(1) #second

print(result)


[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female']]


In [46]:
import pandas as pd

df = pd.DataFrame(result, columns = ["name","height", "mass","gender"])

df.to_csv("starwarapi.csv")

NameError: ignored

Web scrapping

In [ ]:
#web scrapping
#gazpacho

In [7]:
!pip install gazpacho

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7462 sha256=a39e74ac5349d3298b579d509ebcf9d2e3f5e57f75d8b5f7d38d1f8431629794
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [ ]:
!pip list | grep "gaz" #grep เอาไว้หาเหมือน regular expression

gazpacho                         1.1


In [8]:
from gazpacho import Soup
from requests import get

url ="https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

response = get(url)

imdb = Soup(response.text) #แปลงข้อมูลให้กลายเป็น soup object เพื่อให้ดึงง่ายขึ้น

In [9]:
title_list = imdb.find("h3", {"class": "lister-item-header"})

In [20]:
titles = [title.strip() for title in title_list]
print(titles)

['1. The Shawshank Redemption (1994)', '2. The Godfather (1972)', '3. The Dark Knight (2008)', "4. Schindler's List (1993)", '5. 12 Angry Men (1957)', '6. The Godfather Part II (1974)', '7. The Lord of the Rings: The Return of the King (2003)', '8. Pulp Fiction (1994)', '9. Spider-Man: Across the Spider-Verse (2023)', '10. Inception (2010)', '11. The Lord of the Rings: The Fellowship of the Ring (2001)', '12. Fight Club (1999)', '13. Forrest Gump (1994)', '14. The Good, the Bad and the Ugly (1966)', '15. The Lord of the Rings: The Two Towers (2002)', '16. Interstellar (2014)', '17. Goodfellas (1990)', '18. The Matrix (1999)', "19. One Flew Over the Cuckoo's Nest (1975)", '20. Star Wars: Episode V - The Empire Strikes Back (1980)', '21. Oppenheimer (2023)', '22. The Silence of the Lambs (1991)', '23. Se7en (1995)', '24. Saving Private Ryan (1998)', '25. Terminator 2: Judgment Day (1991)', '26. The Green Mile (1999)', '27. Star Wars: Episode IV - A New Hope (1977)', '28. City of God (200

In [10]:
for title in title_list:
    print(title.strip())

1. The Shawshank Redemption (1994)
2. The Godfather (1972)
3. The Dark Knight (2008)
4. Schindler's List (1993)
5. 12 Angry Men (1957)
6. The Godfather Part II (1974)
7. The Lord of the Rings: The Return of the King (2003)
8. Pulp Fiction (1994)
9. Spider-Man: Across the Spider-Verse (2023)
10. Inception (2010)
11. The Lord of the Rings: The Fellowship of the Ring (2001)
12. Fight Club (1999)
13. Forrest Gump (1994)
14. The Good, the Bad and the Ugly (1966)
15. The Lord of the Rings: The Two Towers (2002)
16. Interstellar (2014)
17. Goodfellas (1990)
18. The Matrix (1999)
19. One Flew Over the Cuckoo's Nest (1975)
20. Star Wars: Episode V - The Empire Strikes Back (1980)
21. Oppenheimer (2023)
22. The Silence of the Lambs (1991)
23. Se7en (1995)
24. Saving Private Ryan (1998)
25. Terminator 2: Judgment Day (1991)
26. The Green Mile (1999)
27. Star Wars: Episode IV - A New Hope (1977)
28. City of God (2002)
29. Spirited Away (2001)
30. Life Is Beautiful (1997)
31. It's a Wonderful Life 

In [15]:
runtimes = imdb.find("span",{"class":"runtime"})
runtimes =[runtime.strip() for runtime in runtimes]
print(runtimes)

['142 min', '175 min', '152 min', '195 min', '96 min', '202 min', '201 min', '154 min', '140 min', '148 min', '178 min', '139 min', '142 min', '178 min', '179 min', '169 min', '145 min', '136 min', '133 min', '124 min', '180 min', '118 min', '127 min', '169 min', '137 min', '189 min', '121 min', '130 min', '125 min', '116 min', '130 min', '207 min', '133 min', '130 min', '116 min', '151 min', '117 min', '132 min', '155 min', '106 min', '110 min', '150 min', '106 min', '88 min', '119 min', '109 min', '89 min', '112 min', '102 min', '165 min']


In [23]:
import pandas as pd

df = pd.DataFrame({
    "title" : titles,
    "runtime": runtimes
})

In [24]:
df.to_csv("imdb_data.csv")

In [27]:
#numpy = numerical python
import numpy as np

num = [1,2,3,4,5]

num_arr = np.array(num)
Multiply = num_arr *2
print(Multiply)

[ 2  4  6  8 10]


In [33]:
#statistical basic cal
np.sum(num_arr)
np.mean(num_arr)
np.std(num_arr)

1.4142135623730951

In [32]:
num_arr.mean()

3.0

In [37]:
#numpy as matric
m1 = np.array([
    [1,2],
    [3,4]
])

m1 *5

array([[ 5, 10],
       [15, 20]])

In [38]:
m2 = np.array([
    [5,5],
    [4,2]
])

In [40]:
print(m1,"\n",m2) #"\n" = new line

[[1 2]
 [3 4]] 
 [[5 5]
 [4 2]]


In [42]:
m1.dot(m2) #จะคูณแบบ matrix
np.dot(m1,m2)

array([[13,  9],
       [31, 23]])

In [49]:
#intro to pandas
import pandas as pd
import numpy as np

In [54]:
!cat Hotel.csv

id,hotel,location,price
1,Accor,Thailand,50
2,Ibis,Italy,60
3,London,UK,35
4,Seoul,Korea,30
5,le concord,USA,25

In [55]:
hotel = pd.read_csv("Hotel.csv")

In [59]:
hotel.shape #(5 row 4 column)

(5, 4)

In [60]:
hotel.info() # อารมณ์ glimpse in R

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        5 non-null      int64 
 1   hotel     5 non-null      object
 2   location  5 non-null      object
 3   price     5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes


In [63]:
hotel.describe(include="all")

id  hotel  location     price
count   5.000000      5         5   5.00000
unique       NaN      5         5       NaN
top          NaN  Accor  Thailand       NaN
freq         NaN      1         1       NaN
mean    3.000000    NaN       NaN  40.00000
std     1.581139    NaN       NaN  14.57738
min     1.000000    NaN       NaN  25.00000
25%     2.000000    NaN       NaN  30.00000
50%     3.000000    NaN       NaN  35.00000
75%     4.000000    NaN       NaN  50.00000
max     5.000000    NaN       NaN  60.00000

In [64]:
hotel["location"] #ดึง column มาดูแบบที่ 1

0    Thailand
1       Italy
2          UK
3       Korea
4         USA
Name: location, dtype: object

In [67]:
hotel["price"]#ดึง column มาดูแบบที่ 2

0    50
1    60
2    35
3    30
4    25
Name: price, dtype: int64

In [69]:
#create new column
hotel["vat"] = hotel["price"] * 0.07

hotel

id       hotel  location  price   vat
0   1       Accor  Thailand     50  3.50
1   2        Ibis     Italy     60  4.20
2   3      London        UK     35  2.45
3   4       Seoul     Korea     30  2.10
4   5  le concord       USA     25  1.75

In [71]:
#filter rows by query
value_hotel = hotel.query("price > 40")

In [72]:
value_hotel.to_csv("value_hotel")

In [74]:
#drop column axis=0 คือ index 1 คือ column
hotel.drop(["id","vat"], axis = 1)

hotel  location  price
0       Accor  Thailand     50
1        Ibis     Italy     60
2      London        UK     35
3       Seoul     Korea     30
4  le concord       USA     25

In [75]:
new_hotel = hotel.drop(["id","vat"], axis = 1) #ถ้าไม่ใส่เข้าไปใน new_hotel จะทำให้ df เดิมยังมี column ครบ


In [76]:
new_hotel

hotel  location  price
0       Accor  Thailand     50
1        Ibis     Italy     60
2      London        UK     35
3       Seoul     Korea     30
4  le concord       USA     25

In [79]:
hotel.drop("vat", axis=1, inplace = True)

In [81]:
hotel.query("price > 30 or location == 'UK'")

id   hotel  location  price
0   1   Accor  Thailand     50
1   2    Ibis     Italy     60
2   3  London        UK     35

In [ ]:
#sklearn => machine learning most popular python
#template in sklearn to train_test_split

In [82]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pandas as pd

In [87]:
mtcars = pd.read_csv("https://gist.githubusercontent.com/ZeccaLehn/4e06d2575eb9589dbe8c365d61cb056c/raw/898a40b035f7c951579041aecbfb2149331fa9f6/mtcars.csv")

In [88]:
mtcars.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [94]:
#prepare 50-80%
X = mtcars[["hp","wt","am"]]
y = mtcars["mpg"]

In [95]:
#split data
X_train, X_test, y_train, y_test = train_test_split (X,y,test_size=0.2, random_state=42) # rando_state = set.seed in R

In [104]:
#train model
model = LinearRegression()
model.fit(X_train,y_train)
#test model/ scoring
pred = model.predict(X_test)

#MAE mean absolute error
MAE = np.mean(np.absolute(y_test- pred))

#MSE
MSE = np.mean((y_test - pred)**2)
#evaluate model